name: Label PRs according to criteria

on:
  pull_request:
    paths:
    - 'Formula/*.rb'

jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.3'
      - run: gem install octokit
      - run: ruby .github/workflows/scripts/add-labels.rb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
