name: Publish and commit bottles

on: repository_dispatch

jobs:
  upload:
    runs-on: ubuntu-latest
    env:
      HOMEBREW_DEVELOPER: 1
      HOMEBREW_FORCE_HOMEBREW_ON_LINUX: 1
      HOMEBREW_NO_ANALYTICS: 1
      HOMEBREW_NO_AUTO_UPDATE: 1
    steps:
      - name: Post comment once started
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
          script: |
            const run_id = process.env.GITHUB_RUN_ID
            const actor = context.actor
            const pr = context.payload.client_payload.pull_request
            console.log("run_id=" + run_id)
            console.log("actor=" + actor)
            console.log("pr=" + pr)

            const repository = context.repo.owner + '/' + context.repo.repo
            const url = 'https://github.com/' + repository + '/actions/runs/' + run_id

            let comment = ''
            if (actor == 'BrewTestBot') {
                comment += ':robot: A scheduled task'
            } else {
                comment += ':shipit: @' + actor
            }
            comment += ' has [triggered a merge](' + url + ').'

            github.issues.createComment({
              ...context.repo,
              issue_number: pr,
              body: comment
            })
      - name: Update Homebrew
        run: |
          brew update-reset $(brew --repository)
      - name: Checkout tap
        uses: actions/checkout@v2
        with:
          token: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
          fetch-depth: 0
      - name: Setup tap
        run: |
          rm -rf $(brew --repository ${{github.repository}})
          ln -s $GITHUB_WORKSPACE $(brew --repository ${{github.repository}})
      - name: Setup git
        uses: Homebrew/actions/git-user-config@master
      - name: Pull bottles
        env:
          HOMEBREW_GITHUB_API_TOKEN: ${{secrets.GITHUB_TOKEN}}
          HOMEBREW_BINTRAY_USER: brewtestbot
          HOMEBREW_BINTRAY_KEY: ${{secrets.HOMEBREW_BINTRAY_KEY}}
        run: |
          brew pr-pull --verbose ${{github.event.client_payload.pull_request}}
      - name: Push commits
        uses: Homebrew/actions/git-try-push@master
      - name: Post comment on failure
        if: ${{!success()}}
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.HOMEBREW_GITHUB_API_TOKEN}}
          script: |
            const run_id = process.env.GITHUB_RUN_ID
            const actor = context.actor
            const pr = context.payload.client_payload.pull_request
            const repository = context.repo.owner + '/' + context.repo.repo
            const url = 'https://github.com/' + repository + '/actions/runs/' + run_id

            console.log("run_id=" + run_id)
            console.log("actor=" + actor)
            console.log("pr=" + pr)

            let comment = ':warning: '
            if (actor != 'BrewTestBot') {
                comment += '@' + actor
            }
            let status = '${{job.status}}'.toLowerCase()
            comment += ' bottle publish [' + status + '](' + url + ').'

            github.issues.createComment({
              ...context.repo,
              issue_number: pr,
              body: comment
            })

            const reviews = await github.pulls.listReviews({
              ...context.repo,
              pull_number: pr
            })

            for (const review of reviews.data) {
              if (review.state != "APPROVED")
                continue

              github.pulls.dismissReview({
                ...context.repo,
                pull_number: pr,
                review_id: review.id,
                message: "bottle publish failed"
              });
            }
